import 'dotenv/config';
import express from 'express';
import Parser from 'rss-parser';
import { ActionRowBuilder,ButtonBuilder,ButtonStyle,ChannelType,Client,EmbedBuilder,Events,GatewayIntentBits,PermissionFlagsBits,REST,Routes,SlashCommandBuilder,StringSelectMenuBuilder,StringSelectMenuOptionBuilder } from 'discord.js';
const TOKEN=process.env.DISCORD_TOKEN,CLIENT_ID=process.env.CLIENT_ID,GUILD_ID=process.env.GUILD_ID,YOUTUBE_CHANNEL_ID=process.env.YOUTUBE_CHANNEL_ID,PORT=Number(process.env.PORT||3000),WEBHOOK_SECRET=process.env.WEBHOOK_SECRET||'';
if(!TOKEN||!CLIENT_ID||!GUILD_ID){console.error('Faltan DISCORD_TOKEN, CLIENT_ID o GUILD_ID');process.exit(1)}
const client=new Client({intents:[GatewayIntentBits.Guilds,GatewayIntentBits.GuildMembers,GatewayIntentBits.GuildVoiceStates,GatewayIntentBits.GuildMessages,GatewayIntentBits.MessageContent]});
const parser=new Parser();let lastYoutubeVideoId=null;const tempVoiceChannels=new Set(),giveaways=new Map();
const TIKTOK_URL='https://www.tiktok.com/@alantorresvr?lang=es';
const LIVE_ROLE='🔴 Directos',LIVE_CHANNEL='🔴・directos-y-videos',COMMAND_CHANNEL='🤖・comandos-alan';
const commandData=[
 new SlashCommandBuilder().setName('directo').setDescription('Anuncia que Alan está EN VIVO en TikTok.').setDefaultMemberPermissions(PermissionFlagsBits.Administrator),
 new SlashCommandBuilder().setName('mensaje').setDescription('Envía un mensaje bonito del bot al canal que elijas.')
   .addChannelOption(o=>o.setName('canal').setDescription('Canal donde quieres publicar').addChannelTypes(ChannelType.GuildText,ChannelType.GuildAnnouncement).setRequired(true))
   .addStringOption(o=>o.setName('mensaje').setDescription('Texto que quieres publicar').setRequired(true).setMaxLength(4000))
   .addStringOption(o=>o.setName('titulo').setDescription('Título opcional del mensaje').setRequired(false).setMaxLength(256))
   .setDefaultMemberPermissions(PermissionFlagsBits.Administrator),
 new SlashCommandBuilder().setName('publicar').setDescription('Anuncia un video/publicación.').addStringOption(o=>o.setName('plataforma').setDescription('Plataforma').setRequired(true)).addStringOption(o=>o.setName('titulo').setDescription('Título').setRequired(true)).addStringOption(o=>o.setName('url').setDescription('Enlace').setRequired(true)).addStringOption(o=>o.setName('mensaje').setDescription('Texto extra').setRequired(false)).setDefaultMemberPermissions(PermissionFlagsBits.ManageGuild),
 new SlashCommandBuilder().setName('timeout').setDescription('Silencia temporalmente a un usuario.').addUserOption(o=>o.setName('usuario').setDescription('Usuario').setRequired(true)).addIntegerOption(o=>o.setName('minutos').setDescription('Minutos').setRequired(true).setMinValue(1).setMaxValue(40320)).addStringOption(o=>o.setName('razon').setDescription('Razón').setRequired(false)).setDefaultMemberPermissions(PermissionFlagsBits.ModerateMembers),
 new SlashCommandBuilder().setName('kick').setDescription('Expulsa a un usuario.').addUserOption(o=>o.setName('usuario').setDescription('Usuario').setRequired(true)).addStringOption(o=>o.setName('razon').setDescription('Razón').setRequired(false)).setDefaultMemberPermissions(PermissionFlagsBits.KickMembers),
 new SlashCommandBuilder().setName('ban').setDescription('Banea a un usuario.').addUserOption(o=>o.setName('usuario').setDescription('Usuario').setRequired(true)).addStringOption(o=>o.setName('razon').setDescription('Razón').setRequired(false)).setDefaultMemberPermissions(PermissionFlagsBits.BanMembers)
].map(c=>c.toJSON());
async function registerCommands(){const rest=new REST({version:'10'}).setToken(TOKEN);await rest.put(Routes.applicationGuildCommands(CLIENT_ID,GUILD_ID),{body:commandData})}
async function ensurePrivateCommandChannel(guild){await guild.channels.fetch();await guild.roles.fetch();let ch=guild.channels.cache.find(c=>c.name===COMMAND_CHANNEL&&c.type===ChannelType.GuildText);if(ch)return ch;const alan=guild.roles.cache.find(r=>r.name==='👑 Alan');const me=guild.members.me;const perms=[{id:guild.roles.everyone.id,deny:[PermissionFlagsBits.ViewChannel]}];if(alan)perms.push({id:alan.id,allow:[PermissionFlagsBits.ViewChannel,PermissionFlagsBits.SendMessages,PermissionFlagsBits.ReadMessageHistory]});if(me)perms.push({id:me.id,allow:[PermissionFlagsBits.ViewChannel,PermissionFlagsBits.SendMessages,PermissionFlagsBits.ReadMessageHistory]});ch=await guild.channels.create({name:COMMAND_CHANNEL,type:ChannelType.GuildText,topic:'Canal privado de Alan para ejecutar comandos del bot.',permissionOverwrites:perms,reason:'Canal privado solicitado por Alan'});console.log(`🤖 Canal privado creado: #${COMMAND_CHANNEL}`);return ch}
async function announceLive(guild){await guild.channels.fetch();await guild.roles.fetch();const ch=guild.channels.cache.find(c=>c.name===LIVE_CHANNEL),role=guild.roles.cache.find(r=>r.name===LIVE_ROLE);if(!ch)throw new Error(`No existe #${LIVE_CHANNEL}`);if(!role)throw new Error(`No existe el rol ${LIVE_ROLE}`);const embed=new EmbedBuilder().setColor(0x8E44AD).setTitle('🔴 ¡ESTAMOS EN VIVO!').setURL(TIKTOK_URL).setDescription('🥽 **AlanTorres VR ya está EN DIRECTO en TikTok.**\n\nPásate al stream, saluda en el chat y acompáñanos en el directo. 💜').addFields({name:'📱 TikTok',value:`[@alantorresvr](${TIKTOK_URL})`}).setFooter({text:'AlanTorres VR Latinoamérica • EN VIVO'}).setTimestamp();await ch.send({content:`<@&${role.id}> 🔴 **¡YA ESTAMOS EN VIVO!**\n${TIKTOK_URL}`,embeds:[embed],allowedMentions:{roles:[role.id]}})}
async function announceContent(guild,{platform,title,url,message=''}){const ch=guild.channels.cache.find(c=>c.name===LIVE_CHANNEL);if(!ch)return false;const r=guild.roles.cache.find(x=>x.name==='🎬 Nuevos videos');const embed=new EmbedBuilder().setTitle(title).setURL(url).setDescription(message||`Nuevo contenido en ${platform}.`).setFooter({text:`AlanTorresVR • ${platform}`}).setTimestamp();await ch.send({content:`${r?`<@&${r.id}> `:''}🎬 **Nuevo contenido en ${platform}!**`,embeds:[embed]});return true}
async function sendStyledMessage(channel,{title,message}){const embed=new EmbedBuilder().setColor(0x8E44AD).setDescription(message).setFooter({text:'AlanTorres VR Latinoamérica'}).setTimestamp();if(title)embed.setTitle(title);await channel.send({embeds:[embed],allowedMentions:{parse:[]}})}
async function checkYouTube(){if(!YOUTUBE_CHANNEL_ID)return;try{const feed=await parser.parseURL(`https://www.youtube.com/feeds/videos.xml?channel_id=${encodeURIComponent(YOUTUBE_CHANNEL_ID)}`),item=feed.items?.[0];if(!item)return;const id=item.id||item.link;if(!lastYoutubeVideoId){lastYoutubeVideoId=id;return}if(id!==lastYoutubeVideoId){lastYoutubeVideoId=id;const guild=await client.guilds.fetch(GUILD_ID);await guild.channels.fetch();await guild.roles.fetch();await announceContent(guild,{platform:'YouTube',title:item.title||'Nuevo video',url:item.link,message:'¡Ya hay nuevo video!'})}}catch(e){console.error('YouTube RSS:',e.message)}}
async function logAction(guild,text){const ch=guild.channels.cache.find(c=>c.name==='🧾・logs');if(ch)await ch.send(text).catch(()=>{})}
client.once(Events.ClientReady,async c=>{console.log(`✅ ${c.user.tag} conectado.`);await registerCommands();const guild=await client.guilds.fetch(GUILD_ID);await ensurePrivateCommandChannel(guild).catch(e=>console.error('CANAL COMANDOS:',e.message));await checkYouTube();setInterval(checkYouTube,180000)});
client.on(Events.VoiceStateUpdate,async(o,n)=>{const guild=n.guild,create=guild.channels.cache.find(c=>c.name==='➕・Crear sala');if(create&&n.channelId===create.id&&n.member){const c=await guild.channels.create({name:`🔊 ${n.member.displayName}`.slice(0,100),type:ChannelType.GuildVoice,parent:create.parentId,permissionOverwrites:[{id:n.member.id,allow:[PermissionFlagsBits.ManageChannels,PermissionFlagsBits.MoveMembers]}]});tempVoiceChannels.add(c.id);await n.member.voice.setChannel(c).catch(()=>{})}if(o.channelId&&tempVoiceChannels.has(o.channelId)){const c=guild.channels.cache.get(o.channelId);if(c&&c.members.size===0){tempVoiceChannels.delete(c.id);await c.delete('Sala temporal vacía').catch(()=>{})}}});
client.on(Events.InteractionCreate,async interaction=>{try{if(!interaction.isChatInputCommand())return;if(interaction.commandName==='directo'){if(interaction.channel?.name!==COMMAND_CHANNEL)return interaction.reply({content:`❌ Usa /directo únicamente en #${COMMAND_CHANNEL}.`,ephemeral:true});await announceLive(interaction.guild);return interaction.reply({content:'🔴 Directo anunciado correctamente.',ephemeral:true})}if(interaction.commandName==='mensaje'){if(interaction.channel?.name!==COMMAND_CHANNEL)return interaction.reply({content:`❌ Usa /mensaje únicamente en #${COMMAND_CHANNEL}.`,ephemeral:true});const target=interaction.options.getChannel('canal'),message=interaction.options.getString('mensaje'),title=interaction.options.getString('titulo')||'';if(!target?.isTextBased())return interaction.reply({content:'❌ Ese canal no acepta mensajes de texto.',ephemeral:true});await sendStyledMessage(target,{title,message});return interaction.reply({content:`✅ Mensaje enviado a ${target}.`,ephemeral:true})}if(interaction.commandName==='publicar'){await announceContent(interaction.guild,{platform:interaction.options.getString('plataforma'),title:interaction.options.getString('titulo'),url:interaction.options.getString('url'),message:interaction.options.getString('mensaje')||''});return interaction.reply({content:'✅ Publicación anunciada.',ephemeral:true})}if(['timeout','kick','ban'].includes(interaction.commandName)){const user=interaction.options.getUser('usuario'),member=await interaction.guild.members.fetch(user.id).catch(()=>null),reason=interaction.options.getString('razon')||'Sin razón especificada';if(!member)return interaction.reply({content:'No encontré a ese miembro.',ephemeral:true});if(interaction.commandName==='timeout'){const min=interaction.options.getInteger('minutos');await member.timeout(min*60000,reason);await logAction(interaction.guild,`⏱️ ${user.tag} recibió timeout de ${min} min por ${interaction.user.tag}. Razón: ${reason}`)}else if(interaction.commandName==='kick'){await member.kick(reason);await logAction(interaction.guild,`👢 ${user.tag} fue expulsado por ${interaction.user.tag}. Razón: ${reason}`)}else{await member.ban({reason});await logAction(interaction.guild,`🔨 ${user.tag} fue baneado por ${interaction.user.tag}. Razón: ${reason}`)}return interaction.reply({content:'✅ Acción aplicada.',ephemeral:true})}}catch(e){console.error(e);if(interaction.isRepliable()){const p={content:`❌ Error: ${e.message}`,ephemeral:true};if(interaction.deferred||interaction.replied)await interaction.followUp(p).catch(()=>{});else await interaction.reply(p).catch(()=>{})}}});
const app=express();app.use(express.json({limit:'64kb'}));app.get('/health',(req,res)=>res.json({ok:true,bot:client.user?.tag||'starting'}));app.post('/notify',async(req,res)=>{if(!WEBHOOK_SECRET||req.headers.authorization!==`Bearer ${WEBHOOK_SECRET}`)return res.status(401).json({ok:false,error:'Unauthorized'});const{platform,title,url,message}=req.body||{};if(!platform||!title||!url)return res.status(400).json({ok:false,error:'platform, title y url son obligatorios'});try{const guild=await client.guilds.fetch(GUILD_ID);await guild.channels.fetch();await guild.roles.fetch();res.json({ok:await announceContent(guild,{platform,title,url,message})})}catch(e){res.status(500).json({ok:false,error:e.message})}});app.listen(PORT,()=>console.log(`🌐 Webhook escuchando en puerto ${PORT}`));client.login(TOKEN);