import Parser from 'rss-parser';
const DISCORD_TOKEN=process.env.DISCORD_TOKEN,GUILD_ID=process.env.GUILD_ID,API='https://discord.com/api/v10';
const NEWS_CHANNEL='📰・noticias-vr',DEALS_CHANNEL='🎮・juegos-y-ofertas-vr';
const NEWS_INTERVAL_MS=3600000,DEALS_INTERVAL_MS=3600000,START_DELAY_MS=20000;const parser=new Parser();let started=false,newsBusy=false,dealsBusy=false,dealsBaselineReady=false;const seenNews=new Set(),seenDeals=new Set(),newsQueue=[];
const NEWS_FEEDS=[{name:'Road to VR',url:'https://roadtovr.com/feed/'},{name:'UploadVR',url:'https://www.uploadvr.com/feed/'}];
async function discordRequest(path,options={}){const r=await fetch(`${API}${path}`,{...options,headers:{Authorization:`Bot ${DISCORD_TOKEN}`,'Content-Type':'application/json',...(options.headers||{})}});if(!r.ok)throw new Error(`Discord ${r.status}: ${(await r.text()).slice(0,400)}`);if(r.status===204)return null;return r.json()}
async function safeDiscord(path,options={}){try{return await discordRequest(path,options)}catch(e){console.error(`VR-MONITOR Discord ${path}:`,e.message);return null}}
function stripHtml(s=''){return s.replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&nbsp;/g,' ').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;|&apos;|&#x27;/gi,"'").replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/\s+/g,' ').trim()}function truncate(t,m=350){const c=stripHtml(t||'');return c.length<=m?c:`${c.slice(0,m-1).trim()}…`}
async function channels(){const c=await safeDiscord(`/guilds/${GUILD_ID}/channels`);return Array.isArray(c)?c:[]}
async function getExistingChannel(name){const cs=await channels();const ch=cs.find(c=>c.name===name&&c.type===0);if(!ch)console.warn(`VR-MONITOR: no encontré #${name}. No se creará ni modificará automáticamente.`);return ch||null}
async function sendEmbed(id,embed,content=''){return safeDiscord(`/channels/${id}/messages`,{method:'POST',body:JSON.stringify({content,embeds:[embed],allowed_mentions:{parse:[]}})})}
async function recentEmbedUrls(channelId){const messages=await safeDiscord(`/channels/${channelId}/messages?limit=100`);const urls=new Set();if(Array.isArray(messages)){for(const m of messages){for(const e of(m.embeds||[])){if(e.url)urls.add(e.url);for(const f of(e.fields||[])){const matches=String(f.value||'').match(/https?:\/\/[^)\s>]+/g)||[];for(const u of matches)urls.add(u)}}}}return urls}
async function collectNews(){const out=[];for(const f of NEWS_FEEDS){try{const feed=await parser.parseURL(f.url);for(const i of(feed.items||[]).slice(0,12)){const key=i.guid||i.id||i.link||`${f.name}:${i.title}`;if(key&&!seenNews.has(key)){seenNews.add(key);out.push({...i,source:f.name,key})}}}catch(e){console.error(`VR-MONITOR ${f.name}:`,e.message)}}return out.sort((a,b)=>new Date(b.isoDate||b.pubDate||0)-new Date(a.isoDate||a.pubDate||0))}
async function checkNews(){if(newsBusy)return;newsBusy=true;try{const ch=await getExistingChannel(NEWS_CHANNEL);if(!ch)return;const postedUrls=await recentEmbedUrls(ch.id);for(const i of await collectNews()){if(i.link&&postedUrls.has(i.link))continue;if(!newsQueue.some(x=>x.key===i.key))newsQueue.push(i)}newsQueue.sort((a,b)=>new Date(b.isoDate||b.pubDate||0)-new Date(a.isoDate||a.pubDate||0));let i=null;while(newsQueue.length){const candidate=newsQueue.shift();if(candidate.link&&postedUrls.has(candidate.link)){console.log(`📰 Duplicado omitido: ${truncate(candidate.title,90)}`);continue}i=candidate;break}if(i){const sent=await sendEmbed(ch.id,{color:10181046,title:`🥽 ${truncate(i.title,240)}`,url:i.link,description:truncate(i.contentSnippet||i.content||i.summary||'Nueva noticia VR.',500),fields:[{name:'📰 Fuente',value:i.source,inline:true},{name:'🔗 Artículo',value:`[Leer noticia completa](${i.link})`,inline:true}],footer:{text:`AlanTorres VR Latinoamérica • ${newsQueue.length} noticias en cola`},timestamp:new Date(i.isoDate||i.pubDate||Date.now()).toISOString()});if(sent)console.log(`📰 Noticia VR publicada. Quedan ${newsQueue.length} en cola.`)}}finally{newsBusy=false}}
function parseSteamSearch(html){const rows=html.split(/<a[^>]+class="[^"]*search_result_row[^"]*"/i).slice(1),out=[];for(const row of rows.slice(0,60)){const url=row.match(/href="([^"]+)"/i)?.[1]?.replace(/&amp;/g,'&'),appid=row.match(/data-ds-appid="([^"]+)"/i)?.[1]||url?.match(/\/app\/(\d+)/)?.[1],title=stripHtml(row.match(/<span[^>]+class="title"[^>]*>([\s\S]*?)<\/span>/i)?.[1]||''),d=stripHtml(row.match(/discount_pct[^>]*>([\s\S]*?)<\/div>/i)?.[1]||''),pct=Math.abs(Number(d.replace(/[^0-9]/g,'')))||0,finalPrice=stripHtml(row.match(/discount_final_price[^>]*>([\s\S]*?)<\/div>/i)?.[1]||''),originalPrice=stripHtml(row.match(/discount_original_price[^>]*>([\s\S]*?)<\/div>/i)?.[1]||'');if(appid&&title&&url&&pct>=40)out.push({key:`steam:${appid}:${pct}:${finalPrice}`,title,url,pct,finalPrice,originalPrice,platform:'SteamVR'})}return out}
async function fetchSteamDeals(){const r=await fetch('https://store.steampowered.com/search/?specials=1&vrsupport=402&ndl=1',{headers:{'User-Agent':'Mozilla/5.0 AlanTorresVRBot/1.0','Accept-Language':'es-MX,es;q=0.9,en;q=0.7'}});if(!r.ok)throw new Error(`Steam HTTP ${r.status}`);return parseSteamSearch(await r.text())}
async function checkDeals(){if(dealsBusy)return;dealsBusy=true;try{const ch=await getExistingChannel(DEALS_CHANNEL);if(!ch)return;const postedUrls=await recentEmbedUrls(ch.id);const all=[];try{all.push(...await fetchSteamDeals())}catch(e){console.error('VR-MONITOR Steam:',e.message)}const fresh=[];for(const d of all){if(!seenDeals.has(d.key)&&dealsBaselineReady&&!postedUrls.has(d.url))fresh.push(d);seenDeals.add(d.key)}if(!dealsBaselineReady){dealsBaselineReady=true;console.log(`🔥 VR deals baseline listo (${seenDeals.size} ofertas).`);return}const d=fresh.sort((a,b)=>b.pct-a.pct)[0];if(d){const prices=d.originalPrice?`${d.originalPrice} → **${d.finalPrice}**`:`**${d.finalPrice}**`;const sent=await sendEmbed(ch.id,{color:5763719,title:`🔥 ${d.pct}% OFF • ${truncate(d.title,190)}`,url:d.url,description:`🥽 **${d.platform}**\n💰 ${prices}`,footer:{text:'AlanTorres VR Latinoamérica • Juegos y ofertas VR'},timestamp:new Date().toISOString()});if(sent)console.log('🔥 Oferta VR publicada.')}}finally{dealsBusy=false}}
export function startVRMonitor(){if(started)return;started=true;if(!DISCORD_TOKEN||!GUILD_ID)return;setTimeout(async()=>{await checkNews();await checkDeals();setInterval(checkNews,NEWS_INTERVAL_MS);setInterval(checkDeals,DEALS_INTERVAL_MS);console.log('🥽 VR-MONITOR activo: deduplicación persistente por historial de Discord; usa canales existentes.')},START_DELAY_MS)}