import Parser from 'rss-parser';

const DISCORD_TOKEN = process.env.DISCORD_TOKEN;
const GUILD_ID = process.env.GUILD_ID;
const API = 'https://discord.com/api/v10';
const NEWS_CHANNEL='📰・noticias-vr', DEALS_CHANNEL='🎮・juegos-y-ofertas-vr', VR_CATEGORY='🥽 REALIDAD VIRTUAL';
const NEWS_INTERVAL_MS=60*60*1000, DEALS_INTERVAL_MS=60*60*1000, START_DELAY_MS=20*1000;
const parser=new Parser();
let started=false,newsBusy=false,dealsBusy=false,dealsBaselineReady=false;
const seenNews=new Set(),seenDeals=new Set(),newsQueue=[];
const NEWS_FEEDS=[{name:'Road to VR',url:'https://roadtovr.com/feed/'},{name:'UploadVR',url:'https://www.uploadvr.com/feed/'}];
async function discordRequest(path,options={}){const response=await fetch(`${API}${path}`,{...options,headers:{Authorization:`Bot ${DISCORD_TOKEN}`,'Content-Type':'application/json',...(options.headers||{})}});if(!response.ok){const text=await response.text().catch(()=>'');throw new Error(`Discord ${response.status}: ${text.slice(0,400)}`)}if(response.status===204)return null;return response.json()}
async function safeDiscord(path,options={}){try{return await discordRequest(path,options)}catch(e){console.error(`VR-MONITOR Discord ${path}:`,e.message);return null}}
function stripHtml(input=''){return input.replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&nbsp;/g,' ').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;|&apos;/g,"'").replace(/\s+/g,' ').trim()}
function truncate(text,max=350){const clean=stripHtml(text||'');return clean.length<=max?clean:`${clean.slice(0,max-1).trim()}…`}
async function getGuildChannels(){const c=await safeDiscord(`/guilds/${GUILD_ID}/channels`);return Array.isArray(c)?c:[]}
function readOnlyOverwrites(){return [{id:GUILD_ID,type:0,allow:String(1024|65536),deny:String(2048|32768|16384|262144)}]}
async function ensureReadOnlyChannel(name,topic){const channels=await getGuildChannels();let ch=channels.find(c=>c.name===name&&c.type===0);const category=channels.find(c=>c.name===VR_CATEGORY&&c.type===4);if(ch){await safeDiscord(`/channels/${ch.id}`,{method:'PATCH',body:JSON.stringify({parent_id:category?.id||ch.parent_id,topic,permission_overwrites:readOnlyOverwrites()})});return ch}return safeDiscord(`/guilds/${GUILD_ID}/channels`,{method:'POST',body:JSON.stringify({name,type:0,parent_id:category?.id,topic,permission_overwrites:readOnlyOverwrites()})})}
async function sendEmbed(channelId,embed,content=''){return safeDiscord(`/channels/${channelId}/messages`,{method:'POST',body:JSON.stringify({content,embeds:[embed],allowed_mentions:{parse:[]}})})}
async function collectNews(){const found=[];for(const feedInfo of NEWS_FEEDS){try{const feed=await parser.parseURL(feedInfo.url);for(const item of(feed.items||[]).slice(0,12)){const key=item.guid||item.id||item.link||`${feedInfo.name}:${item.title}`;if(key&&!seenNews.has(key)){seenNews.add(key);found.push({...item,source:feedInfo.name,key})}}}catch(e){console.error(`VR-MONITOR ${feedInfo.name}:`,e.message)}}return found.sort((a,b)=>new Date(b.isoDate||b.pubDate||0)-new Date(a.isoDate||a.pubDate||0))}
async function checkNews(){if(newsBusy)return;newsBusy=true;try{const channel=await ensureReadOnlyChannel(NEWS_CHANNEL,'📰 Noticias y novedades VR publicadas poco a poco durante el día por AlanBot. Canal automático de solo lectura.');if(!channel)return;const fresh=await collectNews();for(const item of fresh){if(!newsQueue.some(x=>x.key===item.key))newsQueue.push(item)}newsQueue.sort((a,b)=>new Date(b.isoDate||b.pubDate||0)-new Date(a.isoDate||a.pubDate||0));const item=newsQueue.shift();if(item){await sendEmbed(channel.id,{color:10181046,title:`🥽 ${truncate(item.title,240)}`,url:item.link,description:truncate(item.contentSnippet||item.content||item.summary||'Nueva noticia relacionada con realidad virtual.',500),fields:[{name:'📰 Fuente',value:item.source,inline:true},{name:'🔗 Artículo',value:`[Leer noticia completa](${item.link})`,inline:true}],footer:{text:`AlanTorres VR Latinoamérica • ${newsQueue.length} noticias en cola`},timestamp:new Date(item.isoDate||item.pubDate||Date.now()).toISOString()});console.log(`📰 Noticia VR publicada. Quedan ${newsQueue.length} en cola.`)}else console.log('📰 Sin noticias VR pendientes.')}finally{newsBusy=false}}
function parseSteamSearch(html){const rows=html.split(/<a[^>]+class="[^"]*search_result_row[^"]*"/i).slice(1),out=[];for(const row of rows.slice(0,60)){const href=row.match(/href="([^"]+)"/i)?.[1]?.replace(/&amp;/g,'&');const appid=row.match(/data-ds-appid="([^"]+)"/i)?.[1]||href?.match(/\/app\/(\d+)/)?.[1];const title=stripHtml(row.match(/<span[^>]+class="title"[^>]*>([\s\S]*?)<\/span>/i)?.[1]||'');const d=stripHtml(row.match(/<div[^>]+class="[^"]*discount_pct[^"]*"[^>]*>([\s\S]*?)<\/div>/i)?.[1]||'');const pct=Math.abs(Number(d.replace(/[^0-9]/g,'')))||0;const finalPrice=stripHtml(row.match(/<div[^>]+class="[^"]*discount_final_price[^"]*"[^>]*>([\s\S]*?)<\/div>/i)?.[1]||'');const originalPrice=stripHtml(row.match(/<div[^>]+class="[^"]*discount_original_price[^"]*"[^>]*>([\s\S]*?)<\/div>/i)?.[1]||'');if(appid&&title&&href&&pct>=40)out.push({key:`steam:${appid}:${pct}:${finalPrice}`,title,url:href,pct,finalPrice,originalPrice,platform:'SteamVR'})}return out}
async function fetchSteamDeals(){const r=await fetch('https://store.steampowered.com/search/?specials=1&vrsupport=402&ndl=1',{headers:{'User-Agent':'Mozilla/5.0 AlanTorresVRBot/1.0','Accept-Language':'es-MX,es;q=0.9,en;q=0.7'}});if(!r.ok)throw new Error(`Steam HTTP ${r.status}`);return parseSteamSearch(await r.text())}
function parseQuestDeals(html){const out=[],linkRe=/<a[^>]+href="(\/app\/[^"#?]+)"[^>]*>([\s\S]*?)<\/a>/gi,seen=new Set();let m;while((m=linkRe.exec(html))&&out.length<40){const href=m[1],title=stripHtml(m[2]);if(!title||title.length>120||seen.has(href))continue;const nearby=stripHtml(html.slice(Math.max(0,m.index-450),Math.min(html.length,m.index+m[0].length+650)));const pm=nearby.match(/-(\d{1,2})%/);if(!pm)continue;const pct=Number(pm[1]);if(pct<40)continue;const prices=[...nearby.matchAll(/\$\s?(\d+(?:\.\d{2})?)/g)].map(x=>`$${x[1]}`).slice(0,2);seen.add(href);out.push({key:`quest:${href}:${pct}:${prices.join(':')}`,title,url:`https://queststoredb.com${href}`,pct,finalPrice:prices[0]||'Ver precio',originalPrice:prices[1]||'',platform:'Meta Quest'})}return out}
async function fetchQuestDeals(){const r=await fetch('https://queststoredb.com/on_sale/?sort=-discount',{headers:{'User-Agent':'Mozilla/5.0 AlanTorresVRBot/1.0'}});if(!r.ok)throw new Error(`QuestStoreDB HTTP ${r.status}`);return parseQuestDeals(await r.text())}
async function checkDeals(){if(dealsBusy)return;dealsBusy=true;try{const channel=await ensureReadOnlyChannel(DEALS_CHANNEL,'🎮 Juegos VR, ofertas destacadas y juegos gratis para Meta Quest y SteamVR. Canal automático de solo lectura.');if(!channel)return;const all=[];try{all.push(...await fetchSteamDeals())}catch(e){console.error('VR-MONITOR Steam:',e.message)}try{all.push(...await fetchQuestDeals())}catch(e){console.error('VR-MONITOR QuestStoreDB:',e.message)}const fresh=[];for(const d of all){if(!seenDeals.has(d.key)&&dealsBaselineReady)fresh.push(d);seenDeals.add(d.key)}if(!dealsBaselineReady){dealsBaselineReady=true;console.log(`🔥 VR deals baseline listo (${seenDeals.size} ofertas).`);return}const d=fresh.sort((a,b)=>b.pct-a.pct)[0];if(d){const prices=d.originalPrice?`${d.originalPrice} → **${d.finalPrice}**`:`**${d.finalPrice}**`;await sendEmbed(channel.id,{color:5763719,title:`🔥 ${d.pct}% OFF • ${truncate(d.title,190)}`,url:d.url,description:`🥽 **${d.platform}**\n💰 ${prices}`,footer:{text:'AlanTorres VR Latinoamérica • Juegos y ofertas VR'},timestamp:new Date().toISOString()});console.log('🔥 Oferta VR publicada.')}}finally{dealsBusy=false}}
export function startVRMonitor(){if(started)return;started=true;if(!DISCORD_TOKEN||!GUILD_ID){console.error('VR-MONITOR: faltan credenciales.');return}setTimeout(async()=>{await checkNews();await checkDeals();setInterval(checkNews,NEWS_INTERVAL_MS);setInterval(checkDeals,DEALS_INTERVAL_MS);console.log('🥽 VR-MONITOR activo: 1 noticia por hora + ofertas/juegos cada hora. Noticias iniciales se publican gradualmente.')},START_DELAY_MS)}
